--------------------------------------------------------------------------------------------
-- ▽Reference
---- https://docs.treasuredata.com/display/public/PD/Supported+Presto+and+TD+Functions
---- https://ja.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E3%81%AE%E5%9C%B0%E5%9F%9F
--------------------------------------------------------------------------------------------

SELECT
  td_ip_to_least_specific_subdivision_name(web.td_ip)
 ,case
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Hokkaido') then '北海道'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Aomori') then '青森県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Iwate') then '岩手県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Miyagi') then '宮城県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Akita') then '秋田県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Yamagata') then '山形県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Fukushima-ken') then '福島県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Niigata') then '新潟県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Toyama') then '富山県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Ishikawa') then '石川県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Fukui') then '福井県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Yamanashi') then '山梨県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Nagano') then '長野県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Ibaraki') then '茨城県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Tochigi') then '栃木県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Gunma') then '群馬県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Saitama') then '埼玉県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Chiba') then '千葉県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Tokyo') then '東京都'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kanagawa') then '神奈川県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Gifu') then '岐阜県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Shizuoka') then '静岡県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Aichi') then '愛知県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Mie') then '三重県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Shiga') then '滋賀県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kyoto') then '京都府'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Ōsaka') then '大阪府'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Hyōgo') then '兵庫県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Nara') then '奈良県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Wakayama') then '和歌山県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Tottori') then '鳥取県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Shimane') then '島根県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Okayama') then '岡山県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Hiroshima') then '広島県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Yamaguchi') then '山口県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Tokushima') then '徳島県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kagawa') then '香川県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Ehime') then '愛媛県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kochi') then '高知県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Fukuoka') then '福岡県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Saga') then '佐賀県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Nagasaki') then '長崎県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kumamoto') then '熊本県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Oita') then '大分県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Miyazaki') then '宮崎県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kagoshima') then '鹿児島県'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Okinawa') then '沖縄県'
      else 'unknown' end as td_prefectures

 ,case
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Hokkaido') then '北海道'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Aomori') then '東北'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Iwate') then '東北'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Miyagi') then '東北'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Akita') then '東北'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Yamagata') then '東北'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Fukushima-ken') then '東北'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Niigata') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Toyama') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Ishikawa') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Fukui') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Yamanashi') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Nagano') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Ibaraki') then '関東'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Tochigi') then '関東'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Gunma') then '関東'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Saitama') then '関東'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Chiba') then '関東'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Tokyo') then '関東'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kanagawa') then '関東'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Gifu') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Shizuoka') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Aichi') then '中部'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Mie') then '近畿'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Shiga') then '近畿'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kyoto') then '近畿'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Ōsaka') then '近畿'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Hyōgo') then '近畿'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Nara') then '近畿'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Wakayama') then '近畿'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Tottori') then '中国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Shimane') then '中国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Okayama') then '中国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Hiroshima') then '中国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Yamaguchi') then '中国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Tokushima') then '四国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kagawa') then '四国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Ehime') then '四国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kochi') then '四国'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Fukuoka') then '九州・沖縄'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Saga') then '九州・沖縄'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Nagasaki') then '九州・沖縄'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kumamoto') then '九州・沖縄'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Oita') then '九州・沖縄'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Miyazaki') then '九州・沖縄'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Kagoshima') then '九州・沖縄'
    when regexp_like(td_ip_to_least_specific_subdivision_name(web.td_ip), 'Okinawa') then '九州・沖縄'
      else 'unknown' end as td_prefectures_region8

FROM your_database.your_web_access_table as web
